import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowLeft,
  faBed,
  faCheck,
  faCircleNotch,
  faCookieBite,
  faGem,
  faGifts,
  faHandHoldingDollar,
  faLayerGroup,
  faLocationDot,
  faMartiniGlass,
  faMoneyBills,
  faMugHot,
  faPenToSquare,
  faPlane,
  faPlus,
  faQuestion,
  faRotate,
  faRotateRight,
  faRoute,
  faShirt,
  faSmoking,
  faTag,
  faTaxi,
  faTrashCan,
  faTriangleExclamation,
  faUser,
  faUtensils,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

import { faClipboard, faCopy } from "@fortawesome/free-regular-svg-icons";

export default function registerIconLibrary() {
  library.add(
    faXmark,
    faPlus,
    faCheck,
    faCircleNotch,
    faArrowLeft,
    faRotateRight,
    faPenToSquare,
    faTrashCan,
    faLocationDot,
    faBed,
    faMartiniGlass,
    faMoneyBills,
    faShirt,
    faMugHot,
    faPlane,
    faGem,
    faQuestion,
    faUtensils,
    faCookieBite,
    faGifts,
    faHandHoldingDollar,
    faSmoking,
    faTaxi,
    faRoute,
    faTriangleExclamation,
    faTag,
    faLayerGroup,
    faUser,
    faClipboard,
    faCopy,
    faRotate,
  );
}
