import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowLeft,
  faBed,
  faCheck,
  faCircleNotch,
  faCookieBite,
  faGem,
  faGifts,
  faHandHoldingDollar,
  faLocationDot,
  faMartiniGlass,
  faMoneyBills,
  faMugHot,
  faPenToSquare,
  faPlane,
  faPlus,
  faQuestion,
  faRotateRight,
  faRoute,
  faShirt,
  faSmoking,
  faTaxi,
  faTrashCan,
  faUtensils,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

export default function registerIconLibrary() {
  library.add(
    faXmark,
    faPlus,
    faCheck,
    faCircleNotch,
    faArrowLeft,
    faRotateRight,
    faPenToSquare,
    faTrashCan,
    faLocationDot,
    faBed,
    faMartiniGlass,
    faMoneyBills,
    faShirt,
    faMugHot,
    faPlane,
    faGem,
    faQuestion,
    faUtensils,
    faCookieBite,
    faGifts,
    faHandHoldingDollar,
    faSmoking,
    faTaxi,
    faRoute,
  );
}
