name: Build & Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this application repo
        uses: actions/checkout@v2
      - name: Use Node.js 22
        uses: actions/setup-node@v1
        with:
          node-version: 22
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Build
        shell: bash
        run: npm run build
      - name: Deploy app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: dist
          target: ${{ secrets.DEPLOY_SRC_TARGET }}
          rm: true
          strip_components: 1
